<a href="https://colab.research.google.com/github/christophe-ye-biname/ML_project/blob/master/neural_network_Titanic_dataset_(tuning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
import zipfile
from google.colab import drive


zip_ref = zipfile.ZipFile("titanic.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [ ]:
datas = pd.read_csv('04b6069cf1eff61b0d6f18790fbf5787-fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv')
datas.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
features = ['Pclass','Sex','Age']
dataset = datas[features]
print(dataset)

     Pclass     Sex   Age
0         3    male  22.0
1         1  female  38.0
2         3  female  26.0
3         1  female  35.0
4         3    male  35.0
..      ...     ...   ...
886       2    male  27.0
887       1  female  19.0
888       3  female   NaN
889       1    male  26.0
890       3    male  32.0

[891 rows x 3 columns]


In [ ]:
X = dataset.values
y = datas.iloc[:, 1:2].values

In [ ]:
print(X)

[[3 'male' 22.0]
 [1 'female' 38.0]
 [3 'female' 26.0]
 ...
 [3 'female' nan]
 [1 'male' 26.0]
 [3 'male' 32.0]]


In [ ]:
print(y)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [ ]:
print(X)

[[3 1 22.0]
 [1 0 38.0]
 [3 0 26.0]
 ...
 [3 0 nan]
 [1 1 26.0]
 [3 1 32.0]]


In [ ]:
print(X[:,2:3])

[[22.0]
 [38.0]
 [26.0]
 [35.0]
 [35.0]
 [nan]
 [54.0]
 [2.0]
 [27.0]
 [14.0]
 [4.0]
 [58.0]
 [20.0]
 [39.0]
 [14.0]
 [55.0]
 [2.0]
 [nan]
 [31.0]
 [nan]
 [35.0]
 [34.0]
 [15.0]
 [28.0]
 [8.0]
 [38.0]
 [nan]
 [19.0]
 [nan]
 [nan]
 [40.0]
 [nan]
 [nan]
 [66.0]
 [28.0]
 [42.0]
 [nan]
 [21.0]
 [18.0]
 [14.0]
 [40.0]
 [27.0]
 [nan]
 [3.0]
 [19.0]
 [nan]
 [nan]
 [nan]
 [nan]
 [18.0]
 [7.0]
 [21.0]
 [49.0]
 [29.0]
 [65.0]
 [nan]
 [21.0]
 [28.5]
 [5.0]
 [11.0]
 [22.0]
 [38.0]
 [45.0]
 [4.0]
 [nan]
 [nan]
 [29.0]
 [19.0]
 [17.0]
 [26.0]
 [32.0]
 [16.0]
 [21.0]
 [26.0]
 [32.0]
 [25.0]
 [nan]
 [nan]
 [0.83]
 [30.0]
 [22.0]
 [29.0]
 [nan]
 [28.0]
 [17.0]
 [33.0]
 [16.0]
 [nan]
 [23.0]
 [24.0]
 [29.0]
 [20.0]
 [46.0]
 [26.0]
 [59.0]
 [nan]
 [71.0]
 [23.0]
 [34.0]
 [34.0]
 [28.0]
 [nan]
 [21.0]
 [33.0]
 [37.0]
 [28.0]
 [21.0]
 [nan]
 [38.0]
 [nan]
 [47.0]
 [14.5]
 [22.0]
 [20.0]
 [17.0]
 [21.0]
 [70.5]
 [29.0]
 [24.0]
 [2.0]
 [21.0]
 [nan]
 [32.5]
 [32.5]
 [54.0]
 [12.0]
 [nan]
 [24.0]
 [nan]
 [45.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])

In [ ]:
print(X)

[[3 1 22.0]
 [1 0 38.0]
 [3 0 26.0]
 ...
 [3 0 29.69911764705882]
 [1 1 26.0]
 [3 1 32.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 3 22.0]
 [1.0 0.0 1 38.0]
 [1.0 0.0 3 26.0]
 ...
 [1.0 0.0 3 29.69911764705882]
 [0.0 1.0 1 26.0]
 [0.0 1.0 3 32.0]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

## Part 2 - Using keras hyperparameter tuning

> Bloc en retrait



### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
def createModel(optimizer='adam'):
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return ann

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
model = KerasClassifier(build_fn=createModel, verbose=0)

In [ ]:
from sklearn.model_selection import GridSearchCV
batch_size = [10, 20, 32, 40, 60, 80, 100]
epochs = [10, 30, 50, 60, 70, 80, 90, 100]
optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']
param_grid = dict(batch_size=batch_size, epochs=epochs, optimizer=optimizer)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train, y_train)

In [ ]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.806220 using {'batch_size': 40, 'epochs': 30, 'optimizer': 'Nadam'}


In [ ]:
print(grid_result.best_score_ , grid_result.best_params_)

0.8033897082010905 {'batch_size': 32, 'epochs': 80}


### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = grid_result.best_params_['batch_size'], epochs = grid_result.best_params_['epochs'])

Epoch 1/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4484 - accuracy: 0.7865
Epoch 2/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4486 - accuracy: 0.7823
Epoch 3/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.7865
Epoch 4/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4478 - accuracy: 0.7865
Epoch 5/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4475 - accuracy: 0.7865
Epoch 6/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4471 - accuracy: 0.7809
Epoch 7/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4469 - accuracy: 0.7781
Epoch 8/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4468 - accuracy: 0.7865
Epoch 9/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4468 - accuracy: 0.7865
Epoch 10/80
23/23 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 0.7823
Epoch 11/80
23/23 [

## Part 3 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
print(y_pred)

[[0.11290744]
 [0.11290744]
 [0.2374591 ]
 [0.967175  ]
 [0.5301631 ]
 [0.4106085 ]
 [0.9617265 ]
 [0.96653056]
 [0.44587997]
 [0.53217715]
 [0.12482584]
 [0.8076695 ]
 [0.11290744]
 [0.90936434]
 [0.96985936]
 [0.61101663]
 [0.1352695 ]
 [0.32351124]
 [0.09756574]
 [0.28735998]
 [0.3362736 ]
 [0.97075   ]
 [0.11290744]
 [0.4106085 ]
 [0.5469814 ]
 [0.9617265 ]
 [0.10600498]
 [0.5469814 ]
 [0.8730569 ]
 [0.69972086]
 [0.10312274]
 [0.81505495]
 [0.11825353]
 [0.4106085 ]
 [0.1150811 ]
 [0.4065692 ]
 [0.08904007]
 [0.22143576]
 [0.25272965]
 [0.15063587]
 [0.2610969 ]
 [0.12822792]
 [0.11290744]
 [0.17209914]
 [0.9644718 ]
 [0.11290744]
 [0.11290744]
 [0.9715617 ]
 [0.16012865]
 [0.28391135]
 [0.4106085 ]
 [0.4657749 ]
 [0.90394866]
 [0.15033078]
 [0.4106085 ]
 [0.26378858]
 [0.25558215]
 [0.63419414]
 [0.20753098]
 [0.11290744]
 [0.1389111 ]
 [0.5301631 ]
 [0.94337153]
 [0.41060853]
 [0.52439624]
 [0.10600498]
 [0.95154214]
 [0.22143576]
 [0.90017927]
 [0.9720383 ]
 [0.87665737]
 [0.29

In [ ]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[92 18]
 [20 49]]


0.7877094972067039