<a href="https://colab.research.google.com/github/christophe-ye-biname/ML_project/blob/master/neural_network_Titanic_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
import zipfile
from google.colab import drive


zip_ref = zipfile.ZipFile("titanic.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [ ]:
datas = pd.read_csv('04b6069cf1eff61b0d6f18790fbf5787-fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv')
datas.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
features = ['Pclass','Sex','Age']
dataset = datas[features]
print(dataset)

     Pclass     Sex   Age
0         3    male  22.0
1         1  female  38.0
2         3  female  26.0
3         1  female  35.0
4         3    male  35.0
..      ...     ...   ...
886       2    male  27.0
887       1  female  19.0
888       3  female   NaN
889       1    male  26.0
890       3    male  32.0

[891 rows x 3 columns]


In [ ]:
X = dataset.values
y = datas.iloc[:, 1:2].values

In [ ]:
print(X)

[[3 'male' 22.0]
 [1 'female' 38.0]
 [3 'female' 26.0]
 ...
 [3 'female' nan]
 [1 'male' 26.0]
 [3 'male' 32.0]]


In [ ]:
print(y)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [ ]:
print(X)

[[3 1 22.0]
 [1 0 38.0]
 [3 0 26.0]
 ...
 [3 0 nan]
 [1 1 26.0]
 [3 1 32.0]]


In [ ]:
print(X[:,2:3])

[[22.0]
 [38.0]
 [26.0]
 [35.0]
 [35.0]
 [nan]
 [54.0]
 [2.0]
 [27.0]
 [14.0]
 [4.0]
 [58.0]
 [20.0]
 [39.0]
 [14.0]
 [55.0]
 [2.0]
 [nan]
 [31.0]
 [nan]
 [35.0]
 [34.0]
 [15.0]
 [28.0]
 [8.0]
 [38.0]
 [nan]
 [19.0]
 [nan]
 [nan]
 [40.0]
 [nan]
 [nan]
 [66.0]
 [28.0]
 [42.0]
 [nan]
 [21.0]
 [18.0]
 [14.0]
 [40.0]
 [27.0]
 [nan]
 [3.0]
 [19.0]
 [nan]
 [nan]
 [nan]
 [nan]
 [18.0]
 [7.0]
 [21.0]
 [49.0]
 [29.0]
 [65.0]
 [nan]
 [21.0]
 [28.5]
 [5.0]
 [11.0]
 [22.0]
 [38.0]
 [45.0]
 [4.0]
 [nan]
 [nan]
 [29.0]
 [19.0]
 [17.0]
 [26.0]
 [32.0]
 [16.0]
 [21.0]
 [26.0]
 [32.0]
 [25.0]
 [nan]
 [nan]
 [0.83]
 [30.0]
 [22.0]
 [29.0]
 [nan]
 [28.0]
 [17.0]
 [33.0]
 [16.0]
 [nan]
 [23.0]
 [24.0]
 [29.0]
 [20.0]
 [46.0]
 [26.0]
 [59.0]
 [nan]
 [71.0]
 [23.0]
 [34.0]
 [34.0]
 [28.0]
 [nan]
 [21.0]
 [33.0]
 [37.0]
 [28.0]
 [21.0]
 [nan]
 [38.0]
 [nan]
 [47.0]
 [14.5]
 [22.0]
 [20.0]
 [17.0]
 [21.0]
 [70.5]
 [29.0]
 [24.0]
 [2.0]
 [21.0]
 [nan]
 [32.5]
 [32.5]
 [54.0]
 [12.0]
 [nan]
 [24.0]
 [nan]
 [45.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])

In [ ]:
print(X)

[[3 1 22.0]
 [1 0 38.0]
 [3 0 26.0]
 ...
 [3 0 29.69911764705882]
 [1 1 26.0]
 [3 1 32.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 3 22.0]
 [1.0 0.0 1 38.0]
 [1.0 0.0 3 26.0]
 ...
 [1.0 0.0 3 29.69911764705882]
 [0.0 1.0 1 26.0]
 [0.0 1.0 3 32.0]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
23/23 [==============================] - 1s 1ms/step - loss: 0.6607 - accuracy: 0.6050
Epoch 2/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6456 - accuracy: 0.6216
Epoch 3/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6236 - accuracy: 0.6284
Epoch 4/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6206 - accuracy: 0.6070
Epoch 5/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5984 - accuracy: 0.6204
Epoch 6/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5757 - accuracy: 0.6345
Epoch 7/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5730 - accuracy: 0.6180
Epoch 8/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5934 - accuracy: 0.5926
Epoch 9/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5697 - accuracy: 0.6105
Epoch 10/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5610 - accuracy: 0.6104
Epoch 11/

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
print(y_pred)

[[0.12132603]
 [0.12132603]
 [0.2901005 ]
 [0.9764931 ]
 [0.49130246]
 [0.3709723 ]
 [0.9798564 ]
 [0.97710556]
 [0.34565103]
 [0.4822598 ]
 [0.1338036 ]
 [0.88532513]
 [0.12132603]
 [0.7912896 ]
 [0.96747965]
 [0.6609212 ]
 [0.1427944 ]
 [0.2902256 ]
 [0.09433949]
 [0.40140966]
 [0.3078317 ]
 [0.9613422 ]
 [0.12132603]
 [0.3709723 ]
 [0.581033  ]
 [0.9798564 ]
 [0.108877  ]
 [0.581033  ]
 [0.8904424 ]
 [0.6182992 ]
 [0.10382482]
 [0.8278929 ]
 [0.12807924]
 [0.3709723 ]
 [0.12520632]
 [0.38364452]
 [0.06373879]
 [0.1482197 ]
 [0.18185765]
 [0.04184747]
 [0.20116568]
 [0.13674608]
 [0.12132603]
 [0.19437763]
 [0.9787299 ]
 [0.12132603]
 [0.12132603]
 [0.9455813 ]
 [0.08838862]
 [0.26604724]
 [0.3709723 ]
 [0.33512443]
 [0.7567963 ]
 [0.155559  ]
 [0.3709723 ]
 [0.19746327]
 [0.18692926]
 [0.65288496]
 [0.24587822]
 [0.12132603]
 [0.14590132]
 [0.49130246]
 [0.9801203 ]
 [0.3709723 ]
 [0.5171384 ]
 [0.108877  ]
 [0.9809948 ]
 [0.1482197 ]
 [0.73174876]
 [0.95001304]
 [0.8890517 ]
 [0.30

In [ ]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[100  10]
 [ 26  43]]


0.7988826815642458